cache: packages
sudo: required
warnings_are_errors: true
language: r
r:
- bioc-devel
- bioc-release
r_binary_packages:
- assertthat
- BiocGenerics
- DelayedArray
- DelayedMatrixStats
- dplyr
- ggplot2
- ggrepel
- grr
- htmlwidgets
- igraph
- irlba
- limma
- lmtest
- MASS
- Matrix
- Matrix.utils
- pbapply
- pbmcapply
- pheatmap
- plotly
- plyr
- proxy
- pryr
- pscl
- purrr
- RANN
- Rcpp
- RcppParallel
- reshape2
- reticulate
- RhpcBLASctl
- Rtsne
- S4Vectors
- shiny
- slam
- spdep
- speedglm
- stringr
- SummarizedExperiment
- uwot
- tibble
- tidyr
- viridis
after_success:
- Rscript -e 'covr::codecov()'
notifications:
  slack:
    secure: FH+TwlrNXm1q2RGtIfVJn0pUfzlR9WXRE6mPYLy2y3mRjX+Uo4g6nG2X2cNUXQLapVjb6UWb5plJfDaajUr1AMdnRo9PcgxcRiYDLEaR/yiRPNp7p6rnC7mEbMDywincdGy9g/OhiTLqgwWwE925b9Mpim7zTGDE0Du4dz3VNUm6aQi1xY/S2LT8xnL1Y4/LyYwGzWSy6kyxRgxNKlIDVs28m7cER9xWzTFG0LG3VcWupPujRWYFV3JDuqMp6m4jWQ7gq4v0PIgyj+unZaa2eyE288E9xp5knhgZzvooN0P0IODnLF4GIBh48iyMuapllx1oaDEHRtjOWCljPugNLK1KQrSrnB95o/2BL3d0WtNv40nteaPP7Fed1+NfF2Zu11nSIfbc1fA1gXdk/AriYHalMmdsp45q3EVx3tkJ4bwcU0ox00HbVUJfeAhb/NwOkZzw1+jHSwB61SxRpyaTi81O3vKcBIxRKD+R1GFOYgGOafqqbf/GHsBFJH718iUyih2WV1Y+HktqbZ+yrViyuO/4Gmf352eq4gsvKJ5Kdap9xAjFyQMXrVFJ7Nm4q81z+r3/xs59fWuQyY+LXYyHYy0xygeinM/fAd2oTweeIR4y4DTBR5t673PPh3PC64xGDE3u29LUAcva5xOqUtdvuPM+2wLAHs8qqpqg+yS9aEo=
