#
# Check Monocle3 repository on push event.
# 
# There is information on Github Actions security at
#   URL: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
#
name: Monocle3 check on push
run-name: Check branch ${{ github.ref_name }} on push by ${{ github.actor }}

on: [push]

jobs:
  monocle3_check_on_push:

    # Notes: ubuntu.
    #   o use Ubuntu - there are messages on line about needing to use Ubuntu
    #   o use a Docker container that has the Monocle3 dependencies installed.
    #     see monocle3/src/docker/docker
    #   o jammy is the current long term support version, 22.04 LTS, so it 
    #     should be around for a while (20221103).
    runs-on: ubuntu-jammy

    container:
      # Note:
      #   in order for the GITHUB_TOKEN to work as a credential one must
      #   allow the Monocle3 repository to access the container 'package'.
      #   Navigate to the Packages tab -> <repository> tab -> Package settings ->
      #   Manage Actions access: click on Add Repository; give repository name
      #
      # The following Docker image was pushed to the Docker container registry.
      # image: docker.io/brgew/monocle3_depend:v1.3.0
      #
      # The following three (commented out) lines give credentials for a docker
      # image stored at the Docker container registry.
      # credentials:
      #   username: brgew
      #   password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_READ }}
      #


      # The following Docker image was pushed to the Github container registry,
      # which is found at the Github Packages tab.
      image: ghcr.io/cole-trapnell-lab/monocle3_depend.v1.3.0_20221103:v1

      #
      #
      # The following three uncommented lines give credentials for a Github
      # container registry. There is information about github.ACTOR at
      #   URL: https://docs.github.com/en/actions/learn-github-actions/contexts
      # where there is the statement
      # github.actor	string	The username of the user that triggered the
      #                         initial workflow run. If the workflow run is
      #                         a re-run, this value may differ from
      #                         github.triggering_actor. Any workflow re-runs
      #                         will use the privileges of github.actor, even
      #                         if the actor initiating the re-run
      #                         (github.triggering_actor) has different
      #                         privileges.
      credentials:
        username: ${{ github.ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # TRAVIS: the testthat scripts check for the TRAVIS environment variable
    # in order to choose the correct set of target values and to avoid
    # running interactive code. I keep the name TRAVIS after switching to
    # Github Actions CI.
    # _R_CHECK_TESTS_NLINES_: instruct the devtools::test scripts to output all
    # error lines rather than the last 13. See
    # https://yihui.org/en/2017/12/last-13-lines-of-output/
    env:
      TRAVIS: true
      _R_CHECK_TESTS_NLINES_: 0

    steps:
      # Get current repository contents.
      - uses: actions/checkout@v3
      # Run tests.
      - name: Run R CMD build and R CMD check
        run: |
          R CMD build .
          R CMD check monocle3*tar.gz
        shell: bash
